# syntax=docker/dockerfile:1

FROM tetafro/golang-gcc:1.17-alpine
# STEP4-4では以下は変更しない
# CMD ["go", "version"]

WORKDIR /

RUN mkdir images
RUN mkdir db
RUN mkdir app

COPY go.mod ./
COPY go.sum ./

RUN go mod tidy
RUN go mod download

COPY ./app/*.go .
COPY . .

RUN go build -o build2022/app

EXPOSE 9000

CMD [ "/build2022/app" ]