# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

# STEP4-4では以下は変更しない
CMD ["go", "version"]

COPY go.mod ./
COPY go.sum ./
RUN go mod tidy

COPY *.go ./app

RUN go build -o build2022/app:latest .

EXPOSE 9000
