# syntax=docker/dockerfile:1

FROM tetafro/golang-gcc:1.16-alpine
# STEP4-4では以下は変更しない
# CMD ["go", "version"]

WORKDIR /

RUN mkdir images
RUN mkdir db
RUN mkdir app

COPY go.mod ./
COPY go.sum ./

RUN go mod tidy
RUN go get "github.com/labstack/echo/v4"
RUN go get "github.com/labstack/echo/v4/middleware"
RUN go get "github.com/labstack/gommon/log"
RUN go get "gorm.io/driver/sqlite"
RUN go get "gorm.io/gorm"

WORKDIR /

COPY ./app/*.go .

RUN go build -o build2022/app

EXPOSE 9000

CMD [ "/build2022/app" ]